### PR TITLE
Fix compatibility with latest `ruby-git`

### LINKED ISSUE #259: msync update --noop is broken with git 1.17.x
We recently noticed the msync command fails with the following traceback.
Further investigation turns out git library has been bumped from git 1.14.0 to 1.17.2 (we found the error with 1.17.1 as well) and that is the trigger.
If we pin it to 1.14.0 then we no longer observe the failure.

```
$ /home/zuul/workspace/.bundled_gems/bin/bundle exec msync update --noop
Syncing 'puppet-whazz'
/home/zuul/workspace/.bundled_gems/gems/modulesync-2.5.0/lib/modulesync/repository.rb:37:in `default_branch': undefined method `[]' for nil:NilClass (NoMethodError)
    from /home/zuul/workspace/.bundled_gems/gems/modulesync-2.5.0/lib/modulesync/repository.rb:55:in `switch'
    from /home/zuul/workspace/.bundled_gems/gems/modulesync-2.5.0/lib/modulesync/repository.rb:86:in `prepare_workspace'
    from /home/zuul/workspace/.bundled_gems/gems/modulesync-2.5.0/lib/modulesync.rb:122:in `manage_module'
    from /home/zuul/workspace/.bundled_gems/gems/modulesync-2.5.0/lib/modulesync.rb:178:in `block in update'
    from /home/zuul/workspace/.bundled_gems/gems/modulesync-2.5.0/lib/modulesync.rb:177:in `each'
    from /home/zuul/workspace/.bundled_gems/gems/modulesync-2.5.0/lib/modulesync.rb:177:in `update'
    from /home/zuul/workspace/.bundled_gems/gems/modulesync-2.5.0/lib/modulesync/cli.rb:149:in `update'
    from /home/zuul/workspace/.bundled_gems/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
    from /home/zuul/workspace/.bundled_gems/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
    from /home/zuul/workspace/.bundled_gems/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
    from /home/zuul/workspace/.bundled_gems/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
    from /home/zuul/workspace/.bundled_gems/gems/modulesync-2.5.0/lib/modulesync/cli/thor.rb:21:in `start'
    from /home/zuul/workspace/.bundled_gems/gems/modulesync-2.5.0/bin/msync:24:in `<top (required)>'
    from /home/zuul/workspace/.bundled_gems/bin/msync:25:in `load'
    from /home/zuul/workspace/.bundled_gems/bin/msync:25:in `<main>'
ERROR
```

The list of modules installed.
```
 Installing addressable 2.8.1
 Installing domain_name 0.5.20190701
 Installing faraday 2.7.4
 Installing faraday-net_http 3.0.2
 Installing git 1.17.2
 Installing gitlab 4.19.0
 Installing http-accept 1.7.0
 Installing httparty 0.21.0
 Installing http-cookie 1.0.5
 Installing json_pure 2.6.3
 Installing mime-types 3.4.1
 Installing mime-types-data 3.2023.0218.1
 Installing mini_mime 1.1.2
 Installing minitar 0.9
 Installing modulesync 2.5.0
 Installing multi_xml 0.6.0
 Installing netrc 0.11.0
 Installing octokit 4.25.1
 Installing pathspec 1.1.3
 Installing public_suffix 5.0.1
 Installing puppet-blacksmith 6.1.1
 Installing puppet-modulebuilder 0.3.0
 Installing rchardet 1.8.0
 Installing rest-client 2.1.0
 Installing ruby2_keywords 0.0.5
 Installing sawyer 0.9.2
 Installing terminal-table 3.0.2
 Installing thor 1.2.1
 Installing unf 0.1.4
 Installing unf_ext 0.0.8.2 with native extensions
 Installing unicode-display_width 2.4.2
```

Operating System: Ubuntu Jammy (22.04)
Ruby version: 3.0

### PR DESCRIPTION
**Pull request by alexjfisher**
Since `ruby-git` `1.16.0` it is no longer possible to parse the output of `branch.full` to determine the default branch. (It now only returns `"remotes/origin/HEAD"` where previously it returned `"remotes/origin/HEAD -> origin/master"`)

Fortunately, since `1.17.0` (which was only released a couple of days after `1.16.0`), there is a `Git.default_branch` method we can use instead.

This commit uses the new method if available.  In the future, we can probably drop the old code and require `ruby-git` `>= 1.17.0`, but since the project seems to currently be undergoing quite a bit of development and we might encounter other issues, lets keep it in for now.

Fixes #259

### CODE REVIEW

File: lib/modulesync/repository.rb [hunk 1]
```diff
@@ -31,6 +31,8 @@ def remote_branch_differ?(local_branch, remote_branch)
     end
 
     def default_branch
+      return Git.default_branch(@directory) if Git.respond_to? 'default_branch'
```
Comment (ekohl) [inline lib/modulesync/repository.rb:34]: I'd leave a comment so it's easier to track in the future. And I think the other changes would be needed to please RuboCop
```suggestion
      # Requires ruby-git >= 1.17.0
      return Git.default_branch(@directory) if Git.respond_to?(:default_branch)

```

**Review by ekohl — APPROVED** [review]
Untested, but :+1: to the general approach.

File: lib/modulesync/repository.rb (hunk 1 above)
Comment (alexjfisher) [reply lib/modulesync/repository.rb]: Comment added. I noticed I should have probably used a symbol even before rubocop told me off! :)

**Comment by alexjfisher** [comment]
Something is still very broken.  https://github.com/ruby-git/ruby-git/pull/622/files#r1130938548 isn't helping :)

**Comment by alexjfisher** [comment]
ok.  hacking ruby-git I can see that the git command failing in the cucumber tests is along the lines of
```
stdout: "fatal: 'modules/awesome/puppet-test' does not appear to be a git repository\\nfatal: Could not read from remote repository.\\n\\nPlease make sure you have the correct access rights\\nand the repository exists.\\n"
```

**Comment by bastelfreak** [comment]
side note: is that compatible with older versions of the gem? Should we test that? Or just bump the `git` dependency to `'~> 1.17', '>= 1.17.2'`

**Comment by alexjfisher** [comment]
I didn't want to enforce new versions of the `git` gem as given the amount of change happening right now, users might still want to pin to an earlier stable version in their `modulesync_config` project.

**Comment by alexjfisher** [comment]
@ekohl I give up.  What's so special about my ruby-git branch https://github.com/voxpupuli/modulesync/pull/260/commits/d6275ef5d245d4c8c6150b2c7eab88025795bc30 vs upstream master? https://github.com/voxpupuli/modulesync/pull/260/commits/ca6c2f33877510811358511a318f2c36fd3d6f2b

**Comment by bastelfreak** [comment]
Probably related: https://github.com/voxpupuli/modulesync_config/pull/791

**Review by bastelfreak — APPROVED** [review]
